=== ArcaeaOffline/docs-concept/docs/definitions/schemas/difficulty.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://arcaeaoffline.sevive.xyz/schemas/definitions/difficulty.json",
  "title": "Arcaea Offline Definitions - Difficulty",
  "type": "object",
  "properties": {
    "ratingClass": {
      "type": "integer",
      "minimum": 0
    },
    "rating": {
      "type": "integer",
      "minimum": 0
    },
    "isRatingPlus": {
      "type": "boolean",
      "default": false
    },
    "chartDesigner": {
      "type": "string"
    },
    "jacketDesigner": {
      "type": "string"
    },
    "hasOverridingAudio": {
      "type": "boolean",
      "default": false
    },
    "hasOverridingJacket": {
      "type": "boolean",
      "default": false
    },
    "jacketNight": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "artist": {
      "type": "string"
    },
    "bg": {
      "type": "string"
    },
    "bgInverse": {
      "type": "string"
    },
    "bpm": {
      "type": "string",
      "pattern": "(\\d+|\\d+-\\d+|\\d+\\s-\\s\\d+)"
    },
    "bpmBase": {
      "type": "number",
      "minimum": 0.0
    },
    "addedAt": {
      "type": "string",
      "format": "date-time"
    },
    "version": {
      "type": "string"
    },
    "isLegacy11": {
      "type": "boolean",
      "default": false
    },
    "localizations": {
      "type": "array",
      "items": {
        "$ref": "https://arcaeaoffline.sevive.xyz/schemas/definitions/difficulty-localization.json"
      }
    },
    "chartInfo": {
      "type": "array",
      "items": {
        "$ref": "https://arcaeaoffline.sevive.xyz/schemas/definitions/chart-info.json"
      }
    }
  },
  "required": [
    "ratingClass",
    "rating",
    "isRatingPlus",
    "hasOverridingAudio",
    "hasOverridingJacket",
    "isLegacy11"
  ]
}

=== ArcaeaOffline/docs-concept/docs/definitions/examples/difficulty.json
{
  "ratingClass": 2,
  "rating": 6,
  "isRatingPlus": false,
  "chartDesigner": "luguanluguan",
  "jacketDesigner": "lulushijiandaole",
  "hasOverridingAudio": true,
  "hasOverridingJacket": true,
  "jacketNight": "jacket",
  "title": "Test -RESURRECTION-",
  "artist": "TeST",
  "bg": "base_base",
  "bgInverse": "base_!base",
  "bpm": "100",
  "bpmBase": 100.0,
  "addedAt": "2025-02-05T02:05:00Z",
  "version": "75.0.0",
  "isLegacy11": false,
  "localizations": [
    {
      "lang": "zh-Hans",
      "title": "Test -复活-"
    }
  ],
  "chartInfo": [
    {
      "constant": 6.0,
      "notes": 2221,
      "addedAt": "2025-02-05T02:05:00Z",
      "version": "75.0.0"
    },
    {
      "constant": 11.0,
      "notes": 2221,
      "addedAt": "2024-02-05T02:05:00Z",
      "version": "74.0.0"
    }
  ]
}
